spring:
  application:
    name: SWP391

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SWP391;encrypt=false
    username: sa
    password: admin123@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
